name: Native MinGW Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - '**/CMakeLists.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '**/CMakeLists.txt'
      - '.github/workflows/buildtest.yml'

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure (native MinGW)
      run: |
        Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
        cmake --preset native-mingw

    - name: Build
      run: cmake --build --preset build-mingw

    - name: Run Tests
      run: |
        cd ./build/mingw/src
        .\Audio360Tests.exe

    - name: Install gcovr
      run: pip install gcovr

    - name: Run Code Coverage
      run: |
        Remove-Item -Recurse -Force coverage -ErrorAction SilentlyContinue
        mkdir coverage
        cd ./build/mingw
        gcovr -r ../.. --html --html-details -o ../../coverage/coverage.html --exclude '.*_deps.*' --exclude '.*test.*' --exclude '.*lib.*'

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage/coverage.html
        path: coverage/coverage.html
