name: Native MSVC Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
      - '**/CMakeLists.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '**/CMakeLists.txt'
      - '.github/workflows/buildtest.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure (native x86_64 Visual Studio)
      run: |
        if (Test-Path build) { Remove-Item -Recurse -Force build }
        cmake --preset native-x86_64-Visual-Studio -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build --preset build-x86_64-VS

    - name: Run Tests
      run: |
        cd .\build\x86_64\src\Debug\
        .\Audio360Tests.exe
